version: "3.8"

services:
  db:
    image: postgres:15.2-alpine
    container_name: "community-portal-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dpg-clh6spvjc5ks73ejvff0-a.frankfurt-postgres.render.com
      - POSTGRES_USER=community_portal_backend_db_user
      - POSTGRES_PASSWORD=bKn4zoRwRNtItPioUMLzFJUcQaUvgisM
    volumes:
      - database_postgres:/var/lib/postgresql/data  
volumes:
  database_postgres: