version: "3.8"

services:
  db:
    image: postgres:15.2-alpine
    container_name: "community-portal-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database_postgres:/var/lib/postgresql/data  
volumes:
  database_postgres:
